### ISSUE TITLE
关于 faas 模块需要改进的汇总

### ISSUE THREAD

**Issue by timqian** [serverless-plus/tencent-sdk#4]
1. 默认返回 10 分钟的日志
2. 需要改变的日志：`[FAAS] Can not get CLS config`: 无法找到指定SCF实例，请部署后调用或检查 SCF 实例名称
3. 需要删除的日志： `[FAAS] Get logs for faas (name: scf-starter-abc-dev, namespace: default, qualifier: $LATEST)`

**Comment by yugasun** [comment]
@timqian 针对 2，这里的报错是用户的 SCF 没有配置 CLS，获取不到指定的 CLS 配置报错。

**Comment by timqian** [comment]
@yugasun 我测试的时候发现不是没有配置 CLS config 的时候会遇到这个错误，而是找不到函数的时候。函数名对的时候可以正常获取日志。这个错误是不是有点问题？

**Comment by yugasun** [comment]
@timqian 这里是通过查询函数详情来获取CLS配置，如果函数不存在，也是获取不到 CLS 配置信息的，因此报错信息一样

**Comment by timqian** [comment]
这样的话需要在每次获取日志之前都 faas.get 一下，性能略差，如果可以的话最好 getLogList 函数可以区分这两个错误，不过如果做不到的话就没办法了。
另外，我们这边希望显示给用户的错误消息都是中文。不知道在 faas 里面能否做到，如果不能我们可能需要定一个错误码的表，我们这边根据这个表给用户中文的错误提示

｜ error code ｜ meaning ｜
｜—-｜—-｜

**Comment by timqian** [comment]
关于错误码和错误消息你觉得怎么样比较好？ @yugasun

**Comment by yugasun** [comment]
@timqian 这个sdk只是提供了接口能力，上层也可以根据 error 的 type 或者 code 做定制化

**Comment by timqian** [comment]
@yugasun 看到 errorType 是字符串，用这个做定制化的话需要保证 errorType 之后不会变化。

还有能否在 README 中说明一下各种 errorType?
