### ISSUE TITLE
getLogList 接口丢失最新数据

### ISSUE THREAD

**Issue by timqian** [serverless-plus/tencent-sdk#5]
在使用 getLogList 轮训最新日志的时候发现:
- 第一次获取日志 `[log1, log2]`
- invoke scf ，等待一段时间之后，getLogList 得到的日志为` [log1, log2, log3]`
- 在5秒内重新调用 getLogList, 得到的日志有可能又变回 `[log1, log2]`

一般间隔 10s 之后可以稳定得到 `[log1, log2, log3]`

**Comment by ole3021** [comment]
这个问题我觉得支持指定日志的起止时间就可以解决。 关于日志查询我还有一下场景需要确认支持，以及使用方法。

@yugasun 日志我们需要支持以下使用场景：

1. 有具体开始截止日期的日志， 需要通过开始截止日期的时间戳获取。 
  * 如果时间跨度过大，一次反回不完回如何处理？ 
  * 日志的时间戳全部是标准UTC时间吗？是否存在用户自定义时间的可能？
2. 只有开始或者截止日期的日志， 默认显示多长时间的日志？
3. 需要显示实时日志，并支持时间间隔， 这个可以由CLI发起，并计算每次轮询日志的开始时间，及间隔。
  * 如果日志过多，一次反回不完回如何处理？ 
4. 需要支持过滤日志， 比如只查看错误日志，或者指定日志， 这部分需要如何配置，是否支持正则过滤。 

@timqian  麻烦一起确认一下

**Comment by yugasun** [comment]
@timqian 函数日志是基于 CLS，日志罗盘都是有延迟的，目前大概是 `30s` 左右，本 SDK 是帮忙请求的云api  [searchlog](https://cloud.tencent.com/document/product/614/16875) 接口，注意 `CLS` 默认保留日志时长 `7` 天。

针对 @ole3021 问题：
1. 目前通过 `limit` 参数来控制返回条数，该参数 sdk 默认为 `10`，使用者可根据个人情况进行查询，通常 cli 也不会显示很多条日志，最好产品则做下限制，比如最多查看最近 10 条，不需要做的很灵活。另外 CLS 查询日志接口，限制日期必须是 UTC+8（上海市区）
2. 默认显示多长时间 SDK 都有说明，目前已经根据 @timqian 要求，从 `1小时` 修改为 `10 分钟`。
3. 建议 CLI 限制最大显示条数，比如 `20`，这个产品决定就好
4. CLI 侧不支持过滤，针对日志状态，有相关接口参数 `status`，参考函数入参说明：https://github.com/serverless-plus/tencent-sdk/blob/master/packages/faas/src/typings/index.ts#L95:18

**Comment by timqian** [comment]
@yugasun 嗯，延迟是一个问题，不过更大的问题是后面查询的日志反而相对前面查的要旧。这个给持续监听日志带来一些麻烦，不过如果是云 API 本身的问题就没办法了，我们这边更改一下实现方式支持一下
